name: Generate 3D Contribution Calendar
on:
  schedule: # execute every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:
jobs:
  build:
    name: Jobs to update 3D contribution calendar
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5

      - name: Generate 3D contribution calendar SVGs
        uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          SETTING_JSON: conf/github-profile-3d-contrib.json

      - name: Push SVGs to the output-3d-contrib branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output-3d-contrib
          build_dir: profile-3d-contrib
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
